version: "3"
services:
  server:
    image: nginx
    volumes:
      - ./lib/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
    environment:
      NGINX_PORT: 80
    networks:
      - go_front

  app:
    tty: true
    stdin_open: true
    links:
      - db
    build:
      context: .
    command: ./pumpkin
    expose:
      - "3000"
    depends_on:
      - db
#      - redis
    networks:
      - go_front
      - go_back
    environment:
      - 'GO111MODULE=on'

  db:
    image: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: kiyama
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    networks:
      - go_back
#    volumes:
#      - "db-data:/var/lib/postgre"

#  redis:
#    image: redis
#    networks:
#      - back
#    expose:
#      - "6379"
#    volumes:
#      - redis:/data

#volumes:
#  db-data:
#    driver: local
#  redis:

networks:
  go_front:
  go_back:
