version: "3"
services:
  server:
    image: nginx
    volumes:
      - ./lib/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
    environment:
      NGINX_PORT: 80
    networks:
      - go_front

  app:
    tty: true
    stdin_open: true
    build:
      context: .
    command: ./pumpkin
    expose:
      - "3000"
#      - redis
    networks:
      - go_front
    environment:
      - 'GO111MODULE=on'

#  redis:
#    image: redis
#    networks:
#      - back
#    expose:
#      - "6379"
#    volumes:
#      - redis:/data

#volumes:
#  redis:

networks:
  go_front:
